services:
  real-world-backend:
    image: modiconme/real-world-backend:latest
    container_name: real-world-backend
    ports:
      - 8080:8080
    networks:
      - real-world

  real-world-frontend:
    image: modiconme/real-world-frontend:latest
    container_name: real-world-frontend
    ports:
      - 80:4200
    networks:
      - real-world

networks:
  real-world:
    driver: bridge
