spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: saeed
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

#  jackson:
#    deserialization:
#      unwrap_root_value: true
#    serialization:
#      wrap_root_value: true

logging:
  level:
    root: info

jwt:
  sign-key: secret-secret-secret-secret-secret-secret # at least 32 character
  token-prefix: Token
  valid-time: 24 # hours
  issuer: app
server:
  port: 8080