spring:
  datasource:
    username: ${POSTGRES_USER}
    url: ${POSTGRES_URL}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  jackson:
    deserialization:
      unwrap_root_value: true

logging:
  level:
    root: info

jwt:
  sign-key: ${JWT_SECRET} # at least 32 character
  token-prefix: Token
  valid-time: 24 # hours
  issuer: app
server:
  port: 8080