-- liquibase formatted sql

-- changeset popov.d:RAP-6
CREATE TABLE tag
(
    id       int8 GENERATED BY DEFAULT AS IDENTITY,
    tag_name varchar(128) NOT NULL,
    CONSTRAINT pk_tag_id PRIMARY KEY (id),
    CONSTRAINT ck_empty_tag_name CHECK (length(trim(tag_name)) > 0)
);