-- liquibase formatted sql

-- changeset popov.d:RAP-4
CREATE TABLE comment
(
    id         int8 GENERATED BY DEFAULT AS IDENTITY,
    body       text      NOT NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now(),
    id_author  bigint    NOT NULL,
    id_article bigint    NOT NULL,
    CONSTRAINT pk_comment_id PRIMARY KEY (id),
    CONSTRAINT fk_user_id FOREIGN KEY (id_author) REFERENCES users (id),
    CONSTRAINT fk_article_id FOREIGN KEY (id_article) REFERENCES article (id),
    CONSTRAINT ck_empty_body CHECK (length(trim(body)) > 0)
);