-- liquibase formatted sql

-- changeset popov.d:RAP-1
CREATE TABLE users
(
    id         int8 GENERATED BY DEFAULT AS IDENTITY,
    email      varchar(128) NOT NULL,
    username   varchar(128) NOT NULL,
    password   varchar(256) NOT NULL,
    bio   varchar(256),
    image varchar(64),
    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_user_id PRIMARY KEY (id),
    CONSTRAINT uq_user_email UNIQUE (email),
    CONSTRAINT uq_user_username UNIQUE (username),
    CONSTRAINT ck_empty_email CHECK (LENGTH(TRIM(email)) > 0),
    CONSTRAINT ck_empty_username CHECK (LENGTH(TRIM(username)) > 0),
    CONSTRAINT ck_empty_password CHECK (LENGTH(TRIM(password)) > 0),
    CONSTRAINT ck_empty_bio CHECK (LENGTH(TRIM(bio)) > 0 OR NULL),
    CONSTRAINT ck_empty_image CHECK (LENGTH(TRIM(image)) > 0 OR NULL)
);