-- liquibase formatted sql

-- changeset popov.d:RAP-3
CREATE TABLE article
(
    id          int8 GENERATED BY DEFAULT AS IDENTITY,
    slug        varchar(255) NOT NULL,
    title       varchar(255) NOT NULL,
    description text         NOT NULL,
    body        text         NOT NULL,
    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW(),
    id_author  bigint    NOT NULL,
    CONSTRAINT pk_article_id PRIMARY KEY (id),
    CONSTRAINT uq_article_slug UNIQUE (slug),
    CONSTRAINT fk_user_id FOREIGN KEY (id_author) REFERENCES users (id),
    CONSTRAINT ck_empty_slug CHECK (LENGTH(TRIM(slug)) > 0),
    CONSTRAINT ck_empty_title CHECK (LENGTH(TRIM(title)) > 0),
    CONSTRAINT ck_empty_description CHECK (LENGTH(TRIM(description)) > 0),
    CONSTRAINT ck_empty_body CHECK (LENGTH(TRIM(body)) > 0)
);